; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_rts = 0
monitor_dtr = 0

; Correct memory settings for Waveshare ESP32-S3-Zero
board_upload.flash_size = 4MB
board_build.arduino.memory_type = qio_qspi
board_build.partitions = default.csv

; Build flags for USB serial and PSRAM
build_flags =
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D BOARD_HAS_PSRAM
    -D CONFIG_ASYNC_TCP_MAX_ACK_TIME=5000
    -D CONFIG_ASYNC_TCP_PRIORITY=10
    -D CONFIG_ASYNC_TCP_QUEUE_SIZE=64
    -D CONFIG_ASYNC_TCP_RUNNING_CORE=1
    -D CONFIG_ASYNC_TCP_STACK_SIZE=4096

lib_deps =
    madhephaestus/ESP32Servo
    ESP32Async/AsyncTCP
    ESP32Async/ESPAsyncWebServer
    bblanchon/ArduinoJson
